name: "Roadrunner Deployment Notifier"
description: "Notifies Roadrunner about a deployment"
inputs:
  identifier:
    description: "One of your application's external identifier you set on Codelitt's backstage."
    required: true
  environment:
    description: "The environment of your application"
    required: true
runs:
  using: "composite"
  steps:
    - name: Send POST request to notify deployment success
      shell: bash
      run: |
        curl -X POST "https://api.roadrunner.codelitt.dev/flows?status=${{ job.status }}&host=${{ inputs.identifier }}&deploy_type=deploy-notification&env=${{ inputs.environment }}"
