name: "Roadrunner Deployment Notifier"
description: 'Notifies Roadrunner about a deployment'
inputs:
  domain:
    description: 'The domain of your application'
    required: true
  environment:
    description: 'The environment of your application'
    required: true
runs:
  using: "composite"
  steps:
    - name: Send POST request to notify deployment success
      if: success()
      run: |
        curl -X POST "https://api.roadrunner.codelitt.dev/flows?status=success&host=${{ inputs.domain }}&deploy_type=deploy-notification&env=${{ inputs.environment }}"
    - name: Send POST request to notify deployment failure
      if: failure()
      run: |
        curl -X POST "https://api.roadrunner.codelitt.dev/flows?status=failure&host=${{ inputs.domain }}&deploy_type=deploy-notification&env=${{ inputs.environment }}"
